import esbuild from "esbuild";
import process from "process";
import { copyFileSync, writeFileSync, watchFile } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// In dev mode, output directly to vault for hot reload
// In prod mode, output to dist/ directory
const outfile = prod
    ? "dist/main.js"
    : "../example-vault/.obsidian/plugins/spark/main.js";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        // Node.js built-ins (available in Electron)
        "fs",
        "os",
        "path",
        "crypto",
        "child_process",
    ],
    format: "cjs",
    platform: "node",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: outfile,
    // React JSX support
    jsx: "automatic",
    loader: {
        ".tsx": "tsx",
        ".ts": "ts",
    },
});

if (prod) {
    await context.rebuild();
    // Copy static files to dist/ for production
    // manifest.json is at repo root (for Obsidian community plugin validation)
    copyFileSync("../manifest.json", "dist/manifest.json");
    copyFileSync("styles.css", "dist/styles.css");
    console.log("✅ Production build complete in dist/");
    process.exit(0);
} else {
    // Copy static files to vault in dev mode
    // manifest.json is at repo root
    copyFileSync("styles.css", "../example-vault/.obsidian/plugins/spark/styles.css");
    copyFileSync("../manifest.json", "../example-vault/.obsidian/plugins/spark/manifest.json");

    // Create .hotreload file to enable Hot Reload plugin
    writeFileSync("../example-vault/.obsidian/plugins/spark/.hotreload", "");

    // Watch styles.css for changes using watchFile (polling-based, more reliable on macOS)
    watchFile("styles.css", { interval: 500 }, (curr, prev) => {
        if (curr.mtimeMs !== prev.mtimeMs) {
            copyFileSync("styles.css", "../example-vault/.obsidian/plugins/spark/styles.css");
            console.log("📝 styles.css updated");
        }
    });

    console.log("🔥 Dev mode active - watching for changes...");
    await context.watch();
}

